const GET_CURRENCY = 'GET_CURRENCY';
const OPEN_MODAL_CURRENCY = 'OPEN_MODAL_CURRENCY';
const CLOSE_MODAL_CURRENCY = 'CLOSE_MODAL_CURRENCY';
const SET_CURRENCY = 'SET_CURRENCY';
const DELETE_CURRENCY = 'DELETE_CURRENCY';
const EDIT_CURRENCY = 'EDIT_CURRENCY';
const CLOSE_ALERT_CURRENCY = 'CLOSE_ALERT_CURRENCY';
const GET_CURRENCY_BY_ID = 'GET_CURRENCY_BY_ID';


export {
	EDIT_CURRENCY,
	DELETE_CURRENCY,
	GET_CURRENCY,
	OPEN_MODAL_CURRENCY,
	SET_CURRENCY,
	CLOSE_MODAL_CURRENCY,
	CLOSE_ALERT_CURRENCY,
	GET_CURRENCY_BY_ID,
};
