const GET_CURRENCY = 'GET_CURRENCY';
const OPEN_MODAL_CURRENCY = 'OPEN_MODAL_CURRENCY';
const CLOSE_MODAL_CURRENCY = 'CLOSE_MODAL_CURRENCY';
const SET_CURRENCY = 'SET_CURRENCY';


export {
	GET_CURRENCY,
	OPEN_MODAL_CURRENCY,
	SET_CURRENCY,
	CLOSE_MODAL_CURRENCY,
};
