const SET_LOCATION = 'SET_ROL_LOCATION';
const BLOCK_LOCATION = 'BLOCK_LOCATION';
const DELETE_LOCATION = 'DELETE_LOCATION';
const OPEN_MODAL_LOCATION = 'OPEN_MODAL_LOCATION';
const CLOSE_MODAL_LOCATION = 'CLOSE_MODAL_LOCATION';
const OPEN_ALERT_LOCATION = 'OPEN_ALERT_LOCATION';
const CLOSE_ALERT_LOCATION = 'CLOSE_ALERT_LOCATION';
const SET_NAME_LOCATION = 'SET_NAME_LOCATION';
const SET_DESCRIPTION_LOCATION = 'SET_DESCRIPTION_LOCATION';
const CLEAN_STATE_LOCATION = 'CLEAN_STATE_LOCATION';

export {
	OPEN_MODAL_LOCATION,
	OPEN_ALERT_LOCATION,
	CLOSE_MODAL_LOCATION,
	CLOSE_ALERT_LOCATION,
	CLEAN_STATE_LOCATION,
	BLOCK_LOCATION,
	DELETE_LOCATION,
	SET_NAME_LOCATION,
	SET_LOCATION,
	SET_DESCRIPTION_LOCATION,
};
