const OPEN_MODAL_PROVIDER = 'OPEN_MODAL_PROVIDER';
const OPEN_ALERT_PROVIDER = 'OPEN_ALERT_PROVIDER';
const CLOSE_ALERT_PROVIDER = 'CLOSE_ALERT_PROVIDER';
const CLEAN_STATE_PROVIDER = 'CLEAN_STATE_PROVIDER';
const CLOSE_MODAL_PROVIDER = 'CLOSE_MODAL_PROVIDER';
const CLEAN_STATE_COUNTRY = 'CLEAN_STATE_COUNTRY';
const EDIT_PROVIDER = 'EDIT_PROVIDER';
const BLOCK_PROVIDER = 'BLOCK_PROVIDER';
const DELETE_PROVIDER = 'DELETE_PROVIDER';
const SET_PROVIDER = 'SET_PROVIDER';
const SET_COUNTRIES_STATES = 'SET_COUNTRIES_STATES';
const SET_COUNTRIES = 'SET_COUNTRIES';

export {
	OPEN_MODAL_PROVIDER,
	OPEN_ALERT_PROVIDER,
	CLOSE_ALERT_PROVIDER,
	CLEAN_STATE_PROVIDER,
	CLOSE_MODAL_PROVIDER,
	CLEAN_STATE_COUNTRY,
	EDIT_PROVIDER,
	BLOCK_PROVIDER,
	DELETE_PROVIDER,
	SET_PROVIDER,
	SET_COUNTRIES_STATES,
	SET_COUNTRIES,
};
