const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CHANGE_PAGE = 'CHANGE_PAGE';
const EDIT_ZONE = 'EDIT_ZONE';
const BLOCK_ZONE = 'BLOCK_ZONE';
const DELETE_ZONE = 'DELETE_ZONE';
const SET_NAME = 'SET_NAME';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const SET_ZONE = 'SET_ROL';

export {
	PAGE_UP,
	PAGE_DOWN,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_ZONE,
	BLOCK_ZONE,
	DELETE_ZONE,
	SET_NAME,
	SET_ZONE,
	SET_DESCRIPTION,
};
