const EDIT_ZONE = 'EDIT_ZONE';
const SET_ZONE = 'SET_ROL_ZONE';
const BLOCK_ZONE = 'BLOCK_ZONE';
const DELETE_ZONE = 'DELETE_ZONE';
const OPEN_MODAL_ZONE = 'OPEN_MODAL_ZONE';
const CLOSE_MODAL_ZONE = 'CLOSE_MODAL_ZONE';
const OPEN_ALERT_ZONE = 'OPEN_ALERT_ZONE';
const CLOSE_ALERT_ZONE = 'CLOSE_ALERT_ZONE';
const SET_NAME_ZONE = 'SET_NAME_ZONE';
const SET_DESCRIPTION_ZONE = 'SET_DESCRIPTION_ZONE';
const CLEAN_STATE_ZONE = 'CLEAN_STATE_ZONE';


export {
	OPEN_MODAL_ZONE,
	OPEN_ALERT_ZONE,
	CLOSE_MODAL_ZONE,
	CLOSE_ALERT_ZONE,
	CLEAN_STATE_ZONE,
	EDIT_ZONE,
	BLOCK_ZONE,
	DELETE_ZONE,
	SET_NAME_ZONE,
	SET_ZONE,
	SET_DESCRIPTION_ZONE,
};
