const SET_USER_RESERVATION = 'SET_USER_RESERVATION';
const SET_HOTEL = 'SET_HOTEL';
const OPEN_MODAL_RESERVATION = 'OPEN_MODAL_RESERVATION';
const OPEN_ALERT_RESERVATION = 'OPEN_ALERT_RESERVATION';
const CLOSE_ALERT_RESERVATION = 'CLOSE_ALERT_RESERVATION';
const UPDATE_VIEW = 'UPDATE_VIEW';
const RST_CLEAN_STATE = 'RST_CLEAN_STATE';
const CLOSE_MODAL_RESERVATION = 'CLOSE_MODAL_RESERVATION';
const EDIT_RESERVATION = 'EDIT_RESERVATION';
const BLOCK_RESERVATION = 'BLOCK_RESERVATION';
const DELETE_RESERVATION = 'DELETE_RESERVATION';
const SET_RESERVATION = 'SET_RESERVATION';
const RST_SET_MODAL = 'RST_SET_MODAL';
const RST_SET_LOAD = 'RST_SET_LOAD';

export {
	SET_USER_RESERVATION,
	SET_HOTEL,
	OPEN_MODAL_RESERVATION,
	OPEN_ALERT_RESERVATION,
	CLOSE_MODAL_RESERVATION,
	CLOSE_ALERT_RESERVATION,
	RST_CLEAN_STATE,
	UPDATE_VIEW,
	EDIT_RESERVATION,
	BLOCK_RESERVATION,
	DELETE_RESERVATION,
	SET_RESERVATION,
	RST_SET_MODAL,
	RST_SET_LOAD,
};
