const PAGE_UP = 'PAGE_UP';
const SET_USER = 'SET_USER';
const PAGE_DOWN = 'PAGE_DOWN';
const SET_HOTEL = 'SET_HOTEL';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CHANGE_PAGE = 'CHANGE_PAGE';
const EDIT_RESERVATION = 'EDIT_RESERVATION';
const BLOCK_RESERVATION = 'BLOCK_RESERVATION';
const DELETE_RESERVATION = 'DELETE_RESERVATION';
const SET_RESERVATION = 'SET_RESERVATION';

export {
	PAGE_UP,
	SET_USER,
	SET_HOTEL,
	PAGE_DOWN,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_RESERVATION,
	BLOCK_RESERVATION,
	DELETE_RESERVATION,
	SET_RESERVATION,
};
