const SB_COLLAPSE_CONFIG = 'SB_COLLAPSE_CONFIG';
const SB_COLLAPSE_TRACKER = 'SB_COLLAPSE_TRACKER';
const SB_COLLAPSE_ADMINISTRATION = 'SB_COLLAPSE_ADMINISTRATION';

export {
	SB_COLLAPSE_CONFIG,
	SB_COLLAPSE_TRACKER,
	SB_COLLAPSE_ADMINISTRATION,
};
