const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const CHANGE_PAGE = 'CHANGE_PAGE';

export {
	PAGE_UP,
	PAGE_DOWN,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
};
