const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_USER_TYPE = 'DELETE_USER_TYPE';
const SET_ROL = 'SET_ROL';
const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const CHANGE_PAGE = 'CHANGE_PAGE';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';
const SEARCH_PAGE_UP = 'SEARCH_PAGE_UP';
const SEARCH_PAGE_DOWN = 'SEARCH_PAGE_DOWN';

export {
	SET_ROL,
	PAGE_UP,
	PAGE_DOWN,
	SET_NAME,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_USER_TYPE,
	SET_BANK_ACCOUNT,
	SEARCH_PAGE_UP,
	SEARCH_PAGE_DOWN,
};

