const SET_NAME_USER_TYPE = 'SET_NAME_USER_TYPE';
const OPEN_MODAL_USER_TYPER = 'OPEN_MODAL_USER_TYPER';
const OPEN_ALERT_USER_TYPE = 'OPEN_ALERT_USER_TYPE';
const CLOSE_ALERT_USER_TYPE = 'CLOSE_ALERT_USER_TYPE';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE_USER_TYPE = 'CLEAN_STATE_USER_TYPE';
const CLOSE_MODAL_USER_TYPE = 'CLOSE_MODAL_USER_TYPE';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_USER_TYPE = 'DELETE_USER_TYPE';
const SET_ROL_USER_TYPE = 'SET_ROL_USER_TYPE';
const CHANGE_PAGE = 'CHANGE_PAGE';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';

export {
	SET_ROL_USER_TYPE,
	SET_NAME_USER_TYPE,
	OPEN_MODAL_USER_TYPER,
	OPEN_ALERT_USER_TYPE,
	CLOSE_MODAL_USER_TYPE,
	CLOSE_ALERT_USER_TYPE,
	CLEAN_STATE_USER_TYPE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_USER_TYPE,
	SET_BANK_ACCOUNT,
};
