const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
const OPEN_PROFILE = 'OPEN_PROFILE';
const CLOSE_PROFILE = 'CLOSE_PROFILE';

export { OPEN_SIDEBAR, CLOSE_SIDEBAR, OPEN_PROFILE, CLOSE_PROFILE };
