const GET_CATEGORY = 'GET_CATEGORY';
const OPEN_MODAL_CATEGORY = 'OPEN_MODAL_CATEGORY';
const CLOSE_MODAL_CATEGORY = 'CLOSE_MODAL_CATEGORY';
const SET_CATEGORY = 'SET_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';
const EDIT_CATEGORY = 'EDIT_CATEGORY';
const CLOSE_ALERT_CATEGORY = 'CLOSE_ALERT_CATEGORY';
const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
const SET_BANKS_ACCOUNTS = 'SET_BANKS_ACCOUNTS';
const SET_ALERT_CATEGORY = 'SET_ALERT_CATEGORY';
const BLOCK_CATEGORY = 'BLOCK_CATEGORY';
const OPEN_ALERT_CATEGORY = 'OPEN_ALERT_CATEGORY';
const CLEAN_STATE_CATEGORY = 'CLEAN_STATE_CATEGORY';

export {
	SET_BANKS_ACCOUNTS,
	EDIT_CATEGORY,
	DELETE_CATEGORY,
	GET_CATEGORY,
	OPEN_MODAL_CATEGORY,
	SET_CATEGORY,
	CLOSE_MODAL_CATEGORY,
	OPEN_ALERT_CATEGORY,
	CLOSE_ALERT_CATEGORY,
	GET_CATEGORY_BY_ID,
	SET_ALERT_CATEGORY,
	BLOCK_CATEGORY,
	CLEAN_STATE_CATEGORY,
};
