const SET_ALERT_MOVEMENT = 'SET_ALERT_MOVEMENT';
const SET_DATA_MOVEMENT = 'SET_DATA_MOVEMENT';
const SET_EVENT_MOVEMENT = 'SET_EVENT_MOVEMENT';

export {
	SET_ALERT_MOVEMENT,
	SET_DATA_MOVEMENT,
	SET_EVENT_MOVEMENT,
};

