const SET_ALERT_MOVEMENT = 'SET_ALERT_MOVEMENT';
const SET_DATA_MOVEMENT = 'SET_DATA_MOVEMENT';
const SET_EVENT_MOVEMENT = 'SET_EVENT_MOVEMENT';
const OPEN_MODAL_EXPENSE_PER_EVENT = 'OPEN_MODAL_EXPENSE_PER_EVENT';
const CLOSE_MODAL_EXPENSE_PER_EVENT = 'CLOSE_MODAL_EXPENSE_PER_EVENT';
const OPEN_MODAL_INCOME_PER_EVENT = 'OPEN_MODAL_INCOME_PER_EVENT';
const CLOSE_MODAL_INCOME_PER_EVENT = 'CLOSE_MODAL_INCOME_PER_EVENT';
const SET_INCOME_PER_EVENT = 'SET_INCOME_PER_EVENT';

export {
	SET_ALERT_MOVEMENT,
	SET_DATA_MOVEMENT,
	SET_EVENT_MOVEMENT,
	OPEN_MODAL_EXPENSE_PER_EVENT,
	CLOSE_MODAL_EXPENSE_PER_EVENT,
	OPEN_MODAL_INCOME_PER_EVENT,
	CLOSE_MODAL_INCOME_PER_EVENT,
	SET_INCOME_PER_EVENT,
};
