const OPEN_MODAL_GUEST = 'OPEN_MODAL_GUEST';
const OPEN_ALERT_GUEST = 'OPEN_ALERT_GUEST';
const CLOSE_ALERT_GUEST = 'CLOSE_ALERT_GUEST';
const CLEAN_STATE_GUEST = 'CLEAN_STATE_GUEST';
const CLOSE_MODAL_GUEST = 'CLOSE_MODAL_GUEST';
const SET_GUEST = 'SET_GUEST';

export {
	OPEN_MODAL_GUEST,
	OPEN_ALERT_GUEST,
	CLOSE_MODAL_GUEST,
	CLOSE_ALERT_GUEST,
	CLEAN_STATE_GUEST,
	SET_GUEST,
};
