const SET_NAME_BANK_ACCOUNT = 'SET_NAME_BANK_ACCOUNT';
const OPEN_MODAL_BANK_ACCOUNT = 'OPEN_MODAL_BANK_ACCOUNT';
const OPEN_ALERT_BANK_ACCOUNT = 'OPEN_ALERT_BANK_ACCOUNT';
const CLOSE_ALERT_BANK_ACCOUNT = 'CLOSE_ALERT_BANK_ACCOUNT';
const CLEAN_STATE_BANK_ACCOUNT = 'CLEAN_STATE_BANK_ACCOUNT';
const CLOSE_MODAL_BANK_ACCOUNT = 'CLOSE_MODAL_BANK_ACCOUNT';
const EDIT_BANK_ACCOUNT = 'EDIT_BANK_ACCOUNT';
const BLOCK_BANK_ACCOUNT = 'BLOCK_BANK_ACCOUNT';
const SET_DESCRIPTION_BANK_ACCOUNT = 'SET_DESCRIPTION_BANK_ACCOUNT';
const DELETE_BANK_ACCOUNT = 'DELETE_BANK_ACCOUNT';
const SET_ROL_BANK_ACCOUNT = 'SET_ROL_BANK_ACCOUNT';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';

export {
	SET_NAME_BANK_ACCOUNT,
	OPEN_MODAL_BANK_ACCOUNT,
	OPEN_ALERT_BANK_ACCOUNT,
	CLOSE_ALERT_BANK_ACCOUNT,
	CLEAN_STATE_BANK_ACCOUNT,
	CLOSE_MODAL_BANK_ACCOUNT,
	EDIT_BANK_ACCOUNT,
	BLOCK_BANK_ACCOUNT,
	SET_DESCRIPTION_BANK_ACCOUNT,
	DELETE_BANK_ACCOUNT,
	SET_ROL_BANK_ACCOUNT,
	SET_BANK_ACCOUNT,
};
