const SET_NAME = 'SET_NAME';
const OPEN_MODAL_ACCESS_EVENT = 'OPEN_MODAL_ACCESS_EVENT';
const OPEN_ALERT_ACCESS_EVENT = 'OPEN_ALERT_ACCESS_EVENT';
const CLOSE_ALERT_ACCESS_EVENT = 'CLOSE_ALERT_ACCESS_EVENT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL_ACCESS_EVENT = 'CLOSE_MODAL_ACCESS_EVENT';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_EVENT = 'DELETE_EVENT';
const SET_ROL = 'SET_ROL';
const SET_EVENT = 'SET_EVENT';
const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const CHANGE_PAGE = 'CHANGE_PAGE';
const GET_TOKEN = 'GET_TOKEN';
const SET_COUNTRIES_STATES = 'SET_COUNTRIES_STATES';
const SET_ACCESS_EVENT = 'SET_ACCESS_EVENT';
const SET_WITH_ROOM = 'SET_WITH_ROOM';
const SET_WITH_TICKET = 'SET_WITH_TICKET';
const OPEN_MODAL_ACCESS = 'OPEN_MODAL_ACCESS';
const ADD_ACCESS = 'ADD_ACCESS';
const SET_HOTEL = 'SET_HOTEL';
const AE_SET_NUMBER_ROOM = 'AE_SET_NUMBER_ROOM';
const AE_SET_NUMBER_TICKET = 'AE_SET_NUMBER_TICKET';
const AE_SET_ACCESS_EVENT = 'AE_SET_ACCESS_EVENT';
const SET_ALERT_QUOTATION = 'SET_ALERT_QUOTATION';

export {
	SET_ROL,
	PAGE_UP,
	SET_NAME,
	PAGE_DOWN,
	OPEN_MODAL_ACCESS_EVENT,
	OPEN_ALERT_ACCESS_EVENT,
	CLOSE_MODAL_ACCESS_EVENT,
	CLOSE_ALERT_ACCESS_EVENT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_EVENT,
	SET_EVENT,
	GET_TOKEN,
	SET_COUNTRIES_STATES,
	SET_ACCESS_EVENT,
	SET_WITH_ROOM,
	SET_WITH_TICKET,
	OPEN_MODAL_ACCESS,
	ADD_ACCESS,
	SET_HOTEL,
	AE_SET_NUMBER_ROOM,
	AE_SET_NUMBER_TICKET,
	AE_SET_ACCESS_EVENT,
	SET_ALERT_QUOTATION,
};
