const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_USER_TYPE = 'DELETE_USER_TYPE';
const SET_ROL = 'SET_ROL';

export {
	CLEAN_STATE,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	DELETE_USER_TYPE,
	OPEN_MODAL,
	CLOSE_MODAL,
	UPDATE_VIEW,
	SET_NAME,
	SET_DESCRIPTION,
	SET_ROL,
};
