const CREATE_USER = 'CREATE_USER';
const EDIT_USER = 'EDIT_USER';
const BLOCK_USER = 'BLOCK_USER';
const DELETE_USER = 'DELETE_USER';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const CLOSE_MODAL = 'CLOSE_MODAL';
const SET_USER = 'SET_USER';
const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const SEARCH_PAGE_UP = 'SEARCH_PAGE_UP';
const SEARCH_PAGE_DOWN = 'SEARCH_PAGE_DOWN ';

export {
	CREATE_USER,
	EDIT_USER,
	BLOCK_USER,
	DELETE_USER,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_ALERT,
	CLOSE_MODAL,
	SET_USER,
	PAGE_UP,
	PAGE_DOWN,
	SEARCH_PAGE_UP,
	SEARCH_PAGE_DOWN,
};
