const CREATE_USER = 'CREATE_USER';
const NEW_CREATE_USER = 'NEW_CREATE_USER';
const EDIT_USER = 'EDIT_USER';
const BLOCK_USER = 'BLOCK_USER';
const DELETE_USER = 'DELETE_USER';
const OPEN_MODAL_USER = 'OPEN_MODAL_USER';
const OPEN_ALERT_USER = 'OPEN_ALERT_USER';
const CLOSE_ALERT_USER = 'CLOSE_ALERT_USER';
const CLOSE_MODAL_USER = 'CLOSE_MODAL_USER';
const SET_USER = 'SET_USER';

export {
	CREATE_USER,
	NEW_CREATE_USER,
	EDIT_USER,
	BLOCK_USER,
	DELETE_USER,
	OPEN_MODAL_USER,
	OPEN_ALERT_USER,
	CLOSE_ALERT_USER,
	CLOSE_MODAL_USER,
	SET_USER,
};
