const OPEN_MODAL_PRODUCT = 'OPEN_MODAL_PRODUCT';
const OPEN_ALERT_PRODUCT = 'OPEN_ALERT_PRODUCT';
const CLOSE_ALERT_PRODUCT = 'CLOSE_ALERT_PRODUCT';
const CLEAN_STATE_PRODUCT = 'CLEAN_STATE_PRODUCT';
const CLOSE_MODAL_PRODUCT = 'CLOSE_MODAL_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const BLOCK_PRODUCT = 'BLOCK_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const SET_PRODUCT = 'SET_PRODUCT';

export {
	OPEN_MODAL_PRODUCT,
	OPEN_ALERT_PRODUCT,
	CLOSE_ALERT_PRODUCT,
	CLEAN_STATE_PRODUCT,
	CLOSE_MODAL_PRODUCT,
	EDIT_PRODUCT,
	BLOCK_PRODUCT,
	DELETE_PRODUCT,
	SET_PRODUCT,
};

