const OPEN_ASSIGN_MODAL_TICKET = 'OPEN_ASSIGN_MODAL_TICKET';
const CLOSE_ASSIGN_MODAL_TICKET = 'CLOSE_ASSIGN_MODAL_TICKET';
const SET_DATA_TICKET_USER = 'SET_DATA_TICKET_USER';
const SET_ALERT_ASSIGN_TICKET = 'SET_ALERT_ASSIGN_TICKET';
const SHOW_LOADING_ASSIGN_TICKET = 'SHOW_LOADING_ASSIGN_TICKET';

export {
	OPEN_ASSIGN_MODAL_TICKET,
	CLOSE_ASSIGN_MODAL_TICKET,
	SET_DATA_TICKET_USER,
	SET_ALERT_ASSIGN_TICKET,
	SHOW_LOADING_ASSIGN_TICKET,
};
