const TK_SET_STATUS = 'TK_SET_STATUS';
const TK_SET_ALERT = 'TK_SET_ALERT';
const PAGE_UP_TOKENS = 'PAGE_UP_TOKENS';
const PAGE_DOWN_TOKENS = 'PAGE_DOWN_TOKENS';
const PAGE_UP_TOKENS_PACK = 'PAGE_UP_TOKENS_PACK';
const PAGE_DOWN_TOKENS_PACK = 'PAGE_DOWN_TOKENS_PACK';

export {
	TK_SET_STATUS,
	TK_SET_ALERT,
	PAGE_UP_TOKENS,
	PAGE_DOWN_TOKENS,
	PAGE_UP_TOKENS_PACK,
	PAGE_DOWN_TOKENS_PACK,
};
