const SET_NAME_BANK = 'SET_NAME_BANK';
const OPEN_MODAL_BANK = 'OPEN_MODAL_BANK';
const OPEN_ALERT_BANK = 'OPEN_ALERT_BANK';
const CLOSE_ALERT_BANK = 'CLOSE_ALERT_BANK';
const CLEAN_STATE_BANK = 'CLEAN_STATE_BANK';
const CLOSE_MODAL_BANK = 'CLOSE_MODAL_BANK';
const EDIT_BANK = 'EDIT_BANK';
const BLOCK_BANK = 'BLOCK_BANK';
const SET_DESCRIPTION_BANK = 'SET_DESCRIPTION_BANK';
const DELETE_BANK = 'DELETE_BANK';
const SET_ROL_BANK = 'SET_ROL_BANK';
const SET_BANK = 'SET_BANK';

export {
	SET_NAME_BANK,
	OPEN_MODAL_BANK,
	OPEN_ALERT_BANK,
	CLOSE_ALERT_BANK,
	CLEAN_STATE_BANK,
	CLOSE_MODAL_BANK,
	EDIT_BANK,
	BLOCK_BANK,
	SET_DESCRIPTION_BANK,
	DELETE_BANK,
	SET_ROL_BANK,
	SET_BANK,
};

