const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_BANK = 'DELETE_BANK';
const SET_ROL = 'SET_ROL';
const SET_BANK = 'SET_BANK';
const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const CHANGE_PAGE = 'CHANGE_PAGE';

export {
	SET_ROL,
	PAGE_UP,
	SET_NAME,
	PAGE_DOWN,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_BANK,
	SET_BANK,
};

