const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_BANK = 'DELETE_BANK';
const SET_ROL = 'SET_ROL';
const SET_BANK = 'SET_BANK';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';
const PAGE_UP_BANK = 'PAGE_UP_BANK';
const PAGE_DOWN_BANK = 'PAGE_DOWN_BANK';
const CHANGE_PAGE = 'CHANGE_PAGE';
const PAGE_UP_AC = 'PAGE_UP_AC';
const PAGE_DOWN_AC = 'PAGE_DOWN_AC';
export {
	SET_ROL,
	PAGE_UP_BANK,
	SET_NAME,
	PAGE_DOWN_BANK,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_BANK,
	SET_BANK,
	SET_BANK_ACCOUNT,
	PAGE_UP_AC,
	PAGE_DOWN_AC,
};

