const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const SET_EMAIL = 'SET_EMAIL';
const SET_PASSWORD = 'SET_PASSWORD';
const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
const SET_CURRENT_USERID = 'SET_CURRENT_USERID';

export {
	LOGIN,
	LOGOUT,
	SET_EMAIL,
	SET_PASSWORD,
	SET_ERROR_STATUS,
	SET_CURRENT_USERID,
};
