const SET_SEARCH = 'SET_SEARCH';
const SET_SEARCH_USERS = 'SET_SEARCH_USERS';
const SET_SEARCH_ZONES = 'SET_SEARCH_ZONES';
const SET_SEARCH_INVITED = 'SET_SEARCH_INVITED';

export {
	SET_SEARCH,
	SET_SEARCH_USERS,
	SET_SEARCH_ZONES,
	SET_SEARCH_INVITED,
};
