const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const SEARCH_PAGE_UP = 'SEARCH_PAGE_UP';
const SEARCH_PAGE_DOWN = 'SEARCH_PAGE_DOWN';
const RESET_PAGINATION = 'RESET_PAGINATION';

export {
	PAGE_UP,
	PAGE_DOWN,
	SEARCH_PAGE_UP,
	SEARCH_PAGE_DOWN,
	RESET_PAGINATION,
};
