const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_ACCESS = 'EDIT_ACCESS';
const BLOCK_ACCESS = 'BLOCK_ACCESS';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_ACCESS = 'DELETE_ACCESS';
const SET_ROL = 'SET_ROL';
const SET_ACCESS = 'SET_ACCESS';
const SET_ACCESS_ACCOUNT = 'SET_ACCESS_ACCOUNT';
const PAGE_UP_ACC = 'PAGE_UP_ACC';
const PAGE_DOWN_ACC = 'PAGE_DOWN_ACC';
const CHANGE_PAGE = 'CHANGE_PAGE';
export {
	SET_ROL,
	PAGE_UP_ACC,
	SET_NAME,
	PAGE_DOWN_ACC,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_ACCESS,
	BLOCK_ACCESS,
	SET_DESCRIPTION,
	DELETE_ACCESS,
	SET_ACCESS,
	SET_ACCESS_ACCOUNT,
};

