const SET_ACCESS = 'SET_ACCESS';
const DELETE_ACCESS = 'DELETE_ACCESS';
const OPEN_MODAL_ACCESS = 'OPEN_MODAL_ACCESS';
const CLOSE_MODAL_ACCESS = 'CLOSE_MODAL_ACCESS';
const OPEN_ALERT_ACCESS = 'OPEN_ALERT_ACCESS';
const CLOSE_ALERT_ACCESS = 'CLOSE_ALERT_ACCESS';

export {
	OPEN_MODAL_ACCESS,
	CLOSE_MODAL_ACCESS,
	OPEN_ALERT_ACCESS,
	CLOSE_ALERT_ACCESS,
	DELETE_ACCESS,
	SET_ACCESS,
};

