const OPEN_MODAL_EXCHANGE_RATE = 'OPEN_MODAL_EXCHANGE_RATE';
const CLOSE_MODAL_EXCHANGE_RATE = 'CLOSE_MODAL_EXCHANGE_RATE';
const OPEN_ALERT_EXCHANGE_RATE = 'OPEN_ALERT_EXCHANGE_RATE';
const CLOSE_ALERT_EXCHANGE_RATE = 'CLOSE_ALERT_EXCHANGE_RATE';
const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
const SET_EXCHANGE_RATE_VALUE = 'SET_EXCHANGE_RATE_VALUE';

export {
	OPEN_MODAL_EXCHANGE_RATE,
	CLOSE_MODAL_EXCHANGE_RATE,
	OPEN_ALERT_EXCHANGE_RATE,
	CLOSE_ALERT_EXCHANGE_RATE,
	SET_EXCHANGE_RATE,
	SET_EXCHANGE_RATE_VALUE,
};
