const PAGE_UP_PAY = 'PAGE_UP_PAY';
const PAGE_DOWN_PAY = 'PAGE_DOWN_PAY';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CHANGE_PAGE = 'CHANGE_PAGE';
const EDIT_PAYMENT = 'EDIT_PAYMENT';
const BLOCK_PAYMENT = 'BLOCK_PAYMENT';
const DELETE_PAYMENT = 'DELETE_PAYMENT';
const SET_NAME = 'SET_NAME';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const SET_PAYMENT = 'SET_ROL';

export {
	PAGE_UP_PAY,
	PAGE_DOWN_PAY,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_PAYMENT,
	BLOCK_PAYMENT,
	DELETE_PAYMENT,
	SET_NAME,
	SET_PAYMENT,
	SET_DESCRIPTION,
};
