
const OPEN_MODAL_PAYMENT = 'OPEN_MODAL_PAYMENT';
const OPEN_ALERT_PAYMENT = 'OPEN_ALERT_PAYMENT';
const CLOSE_ALERT_PAYMENT = 'CLOSE_ALERT_PAYMENT';
const UPDATE_VIEW_PAYMENT = 'UPDATE_VIEW_PAYMENT';
const CLEAN_STATE_PAYMENT = 'CLEAN_STATE_PAYMENT';
const CLOSE_MODAL_PAYMENT = 'CLOSE_MODAL_PAYMENT';
const EDIT_PAYMENT = 'EDIT_PAYMENT';
const BLOCK_PAYMENT = 'BLOCK_PAYMENT';
const DELETE_PAYMENT = 'DELETE_PAYMENT';
const SET_NAME_PAYMENT = 'SET_NAME_PAYMENT';
const SET_DESCRIPTION_PAYMENT = 'SET_DESCRIPTION_PAYMENT';
const SET_PAYMENT = 'SET_PAYMENT';

export {
	OPEN_MODAL_PAYMENT,
	OPEN_ALERT_PAYMENT,
	CLOSE_MODAL_PAYMENT,
	CLOSE_ALERT_PAYMENT,
	CLEAN_STATE_PAYMENT,
	UPDATE_VIEW_PAYMENT,
	EDIT_PAYMENT,
	BLOCK_PAYMENT,
	DELETE_PAYMENT,
	SET_NAME_PAYMENT,
	SET_PAYMENT,
	SET_DESCRIPTION_PAYMENT,
};
