
const OPEN_MODAL_ROOM = 'OPEN_MODAL_ROOM';
const OPEN_ALERT_ROOM = 'OPEN_ALERT_ROOM';
const CLOSE_ALERT_ROOM = 'CLOSE_ALERT_ROOM';
const UPDATE_VIEW_ROOM = 'UPDATE_VIEW_ROOM';
const CLEAN_STATE_ROOM = 'CLEAN_STATE_ROOM';
const CLOSE_MODAL_ROOM = 'CLOSE_MODAL_ROOM';
const EDIT_ROOM = 'EDIT_ROOM';
const BLOCK_ROOM = 'BLOCK_ROOM';
const DELETE_ROOM = 'DELETE_ROOM';
const SET_ROOM = 'SET_ROOM';
const SET_EVENT_ROOM = 'SET_EVENT_ROOM';

export {
	OPEN_MODAL_ROOM,
	OPEN_ALERT_ROOM,
	CLOSE_MODAL_ROOM,
	CLOSE_ALERT_ROOM,
	CLEAN_STATE_ROOM,
	UPDATE_VIEW_ROOM,
	EDIT_ROOM,
	BLOCK_ROOM,
	DELETE_ROOM,
	SET_ROOM,
	SET_EVENT_ROOM,
};
