const PAGE_UP = 'PAGE_UP';
const PAGE_DOWN = 'PAGE_DOWN';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CHANGE_PAGE = 'CHANGE_PAGE';
const EDIT_ROOM = 'EDIT_ROOM';
const BLOCK_ROOM = 'BLOCK_ROOM';
const DELETE_ROOM = 'DELETE_ROOM';
const SET_ROOM = 'SET_ROOM';
const SET_EVENT = 'SET_EVENT';

export {
	PAGE_UP,
	PAGE_DOWN,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_ROOM,
	BLOCK_ROOM,
	DELETE_ROOM,
	SET_ROOM,
	SET_EVENT,
};
