
const OPEN_MODAL_EVENT = 'OPEN_MODAL_EVENT';
const OPEN_ALERT_EVENT = 'OPEN_ALERT_EVENT';
const CLOSE_ALERT_EVENT = 'CLOSE_ALERT_EVENT';
const CLOSE_MODAL_EVENT = 'CLOSE_MODAL_EVENT';
const SET_EVENT = 'SET_EVENT';
const SET_COUNTRIES_STATES_EVENT = 'SET_COUNTRIES_STATES_EVENT';
const SET_COUNTRIES_STATES = 'SET_COUNTRIES_STATES';
const CLEAN_STATE_COUNTRY = 'CLEAN_STATE_COUNTRY';
const SET_PRESALE = 'SET_PRESALE';
const SET_CLOSE_PRESALE = 'SET_CLOSE_PRESALE';
const SET_EVENT_START = 'SET_EVENT_START';
const SET_EVENT_CLOSE = 'SET_EVENT_CLOSE';
const SET_EVENT_NAME = 'SET_EVENT_NAME';
const SET_EVENT_DESCRIPTION = 'SET_EVENT_DESCRIPTION';
const SET_EVENT_STATUS = 'SET_EVENT_STATUS';
const SET_ACCESS_EVENT = 'SET_ACCESS_EVENT';
const SET_WITH_ROOM = 'SET_WITH_ROOM';
const SET_WITH_TICKET = 'SET_WITH_TICKET';
const OPEN_MODAL_ACCESS = 'OPEN_MODAL_ACCESS';
const ADD_ACCESS = 'ADD_ACCESS';
const ID_ACCESS_EVENT = 'ID_ACCESS_EVENT';

export {
	OPEN_MODAL_EVENT,
	CLOSE_MODAL_EVENT,
	OPEN_ALERT_EVENT,
	CLOSE_ALERT_EVENT,
	SET_COUNTRIES_STATES_EVENT,
	SET_EVENT,
	SET_COUNTRIES_STATES,
	CLEAN_STATE_COUNTRY,
	SET_PRESALE,
	SET_CLOSE_PRESALE,
	SET_EVENT_START,
	SET_EVENT_CLOSE,
	SET_EVENT_NAME,
	SET_EVENT_DESCRIPTION,
	SET_EVENT_STATUS,
	SET_ACCESS_EVENT,
	SET_WITH_ROOM,
	SET_WITH_TICKET,
	OPEN_MODAL_ACCESS,
	ADD_ACCESS,
	ID_ACCESS_EVENT,
};
