const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_EVENT = 'DELETE_EVENT';
const SET_ROL = 'SET_ROL';
const SET_EVENT = 'SET_EVENT';
const PAGE_UP_EV = 'PAGE_UP_EV';
const PAGE_DOWN_EV = 'PAGE_DOWN_EV';
const CHANGE_PAGE = 'CHANGE_PAGE';
const GET_TOKEN = 'GET_TOKEN';
const SET_COUNTRIES_STATES = 'SET_COUNTRIES_STATES';

export {
	SET_ROL,
	PAGE_UP_EV,
	SET_NAME,
	PAGE_DOWN_EV,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_EVENT,
	SET_EVENT,
	GET_TOKEN,
	SET_COUNTRIES_STATES,
};
