const SET_NAME = 'SET_NAME';
const OPEN_MODAL_PURCHASE_REQ = 'OPEN_MODAL_PURCHASE_REQ';
const OPEN_ALERT_PURCHASE_REQ = 'OPEN_ALERT_PURCHASE_REQ';
const CLOSE_ALERT_PURCHASE_REQ = 'CLOSE_ALERT_PURCHASE_REQ';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL_PURCHASE_REQ = 'CLOSE_MODAL_PURCHASE_REQ';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_BANK = 'DELETE_BANK';
const SET_ROL = 'SET_ROL';
const SET_BANK = 'SET_BANK';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';
const SET_PURCHASE_REQ = 'SET_PURCHASE_REQ';
const SET_TO_PAY = 'SET_TO_PAY';
const SET_ACCESS_EVENT = 'SET_ACCESS_EVENT';
const PR_SET_USER = 'PR_SET_USER';
const MODAL_USER = 'MODAL_USER';
const CLOSE_MODAL_USER = 'CLOSE_MODAL_USER';
export {
	CLOSE_MODAL_USER,
	MODAL_USER,
	PR_SET_USER,
	SET_ACCESS_EVENT,
	SET_ROL,
	SET_NAME,
	OPEN_MODAL_PURCHASE_REQ,
	OPEN_ALERT_PURCHASE_REQ,
	CLOSE_MODAL_PURCHASE_REQ,
	CLOSE_ALERT_PURCHASE_REQ,
	CLEAN_STATE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_BANK,
	SET_BANK,
	SET_BANK_ACCOUNT,
	SET_PURCHASE_REQ,
	SET_TO_PAY,
};

