const OPEN_MODAL_HOTEL = 'OPEN_MODAL_HOTEL';
const CLOSE_MODAL_HOTEL = 'CLOSE_MODAL_HOTEL';
const OPEN_ALERT_HOTEL = 'OPEN_ALERT_HOTEL';
const CLOSE_ALERT_HOTEL = 'CLOSE_ALERT_HOTEL';
const HT_SET_HOTEL = 'HT_SET_HOTEL';
const GET_HOTEL_BY_ID = 'GET_HOTEL_BY_ID';
const CLEAN_STATE_HOTEL = 'CLEAN_STATE_HOTEL';
const SET_NAME_HOTEL = 'SET_NAME_HOTEL';

export {
	OPEN_MODAL_HOTEL,
	OPEN_ALERT_HOTEL,
	CLOSE_MODAL_HOTEL,
	CLOSE_ALERT_HOTEL,
	HT_SET_HOTEL,
	GET_HOTEL_BY_ID,
	CLEAN_STATE_HOTEL,
	SET_NAME_HOTEL,
};
