const SET_NAME = 'SET_NAME';
const OPEN_MODAL = 'OPEN_MODAL';
const OPEN_ALERT = 'OPEN_ALERT';
const CLOSE_ALERT = 'CLOSE_ALERT';
const UPDATE_VIEW = 'UPDATE_VIEW';
const CLEAN_STATE = 'CLEAN_STATE';
const CLOSE_MODAL = 'CLOSE_MODAL';
const EDIT_USER_TYPE = 'EDIT_USER_TYPE';
const BLOCK_USER_TYPE = 'BLOCK_USER_TYPE';
const SET_DESCRIPTION = 'SET_DESCRIPTION';
const DELETE_BANK = 'DELETE_BANK';
const SET_ROL = 'SET_ROL';
const SET_BANK = 'SET_BANK';
const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';
const SEARCH_PAGE_UP = 'SEARCH_PAGE_UP';
const SEARCH_PAGE_DOWN = 'SEARCH_PAGE_DOWN';
const PAGE_UP_HOTEL = 'PAGE_UP_HOTEL';
const PAGE_DOWN_HOTEL = 'PAGE_DOWN_HOTEL';
const CHANGE_PAGE = 'CHANGE_PAGE';
const SET_PURCHASE_REQ = 'SET_PURCHASE_REQ';
const SET_TO_PAY = 'SET_TO_PAY';
const SET_ACCESS_EVENT = 'SET_ACCESS_EVENT';
const PR_SET_USER = 'PR_SET_USER';
const MODAL_USER = 'MODAL_USER';
const CLOSE_MODAL_USER = 'CLOSE_MODAL_USER';
const DELETE_USER_TYPE = 'DELETE_USER_TYPE';
const GET_HOTEL_BY_ID = 'GET_HOTEL_BY_ID';
const SET_HOTEL = 'SET_HOTEL';
const HT_SET_HOTEL = 'HT_SET_HOTEL';
const EDIT_HOTEL = 'EDIT_HOTEL';

export {
	EDIT_HOTEL,
	SET_HOTEL,
	HT_SET_HOTEL,
	CLOSE_MODAL_USER,
	MODAL_USER,
	PR_SET_USER,
	SET_ACCESS_EVENT,
	SET_ROL,
	PAGE_UP_HOTEL,
	SEARCH_PAGE_UP,
	SEARCH_PAGE_DOWN,
	SET_NAME,
	PAGE_DOWN_HOTEL,
	OPEN_MODAL,
	OPEN_ALERT,
	CLOSE_MODAL,
	CLOSE_ALERT,
	CLEAN_STATE,
	CHANGE_PAGE,
	UPDATE_VIEW,
	EDIT_USER_TYPE,
	BLOCK_USER_TYPE,
	SET_DESCRIPTION,
	DELETE_BANK,
	SET_BANK,
	SET_BANK_ACCOUNT,
	SET_PURCHASE_REQ,
	SET_TO_PAY,
	DELETE_USER_TYPE,
	GET_HOTEL_BY_ID,
};

