const OPEN_MODAL_INCOME_PER_EVENT = 'OPEN_MODAL_INCOME_PER_EVENT';
const CLOSE_MODAL_INCOME_PER_EVENT = 'CLOSE_MODAL_INCOME_PER_EVENT';

export {
	OPEN_MODAL_INCOME_PER_EVENT,
	CLOSE_MODAL_INCOME_PER_EVENT,
};
